# Generated by Django 5.1.2 on 2024-11-09 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_model", models.CharField(max_length=100)),
                ("reviewer_name", models.CharField(max_length=100)),
                ("rating", models.PositiveIntegerField()),
                ("review", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CarBid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bidder_name", models.CharField(max_length=100)),
                ("bid_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bid_date", models.DateTimeField(auto_now_add=True)),
                (
                    "car_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_app.carreview",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Marks",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
