# Generated by Django 5.1.2 on 2024-11-09 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student_app", "0002_carreview_carbid_delete_marks_delete_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carbid",
            name="bid_date",
        ),
    ]
